<?php

define( 'HEADLESS_THEME_PREFIX', 'headless-theme' );
define( 'HEADLESS_THEME_VERSION', '1.0.0' );
define( 'HEADLESS_THEME_ABS_PATH', get_template_directory() );
define( 'HEADLESS_THEME_URL_PATH', get_template_directory_uri() . '/' );
define( 'HEADLESS_THEME_ASSETS_PATH', HEADLESS_THEME_ABS_PATH . '/assets' );
define( 'HEADLESS_THEME_ASSETS_URL_PATH', HEADLESS_THEME_URL_PATH . 'assets' );
define( 'HEADLESS_THEME_INC_PATH', HEADLESS_THEME_ABS_PATH . '/inc' );
define( 'HEADLESS_THEME_INC_URL_PATH', HEADLESS_THEME_URL_PATH . 'inc' );
define( 'HEADLESS_THEME_ADMIN_PATH', HEADLESS_THEME_INC_PATH . '/admin' );
define( 'HEADLESS_THEME_ADMIN_URL_PATH', HEADLESS_THEME_INC_URL_PATH . '/admin' );
define( 'HEADLESS_THEME_TEMPLATES_PATH', HEADLESS_THEME_ABS_PATH . '/templates' );
define( 'HEADLESS_THEME_TEMPLATES_URL_PATH', HEADLESS_THEME_URL_PATH . 'templates' );
define( 'HEADLESS_THEME_BLOCKS_PATH', HEADLESS_THEME_ABS_PATH . '/blocks' );
define( 'HEADLESS_THEME_BLOCKS_URL_PATH', HEADLESS_THEME_URL_PATH . 'blocks' );
